#!/usr/local/bin/python3
"""Episode Browser

Requires Python 3 and mpv. Run in a directory of movies, will play the first file.
Next time, it will play the next one, and so on. Run it with some string to play
the first matching file.

Usage:
    episode watch [--dry-run] [EPISODE]
    episode play [--dry-run] [EPISODE]
    episode update

Options:
    -h --help   Show this screen.
    --version   Show version.
    --dry-run   Don't do anything, just show what would be played

"""
import os
import sys
import requests
from docopt import docopt
from glob import glob

args = docopt(__doc__, version="v0.3")
episodes = list(glob("*.*"))
hidden_data = ".last-episode-id"

def lget(l, idx, default):
    try:
        return l[idx]
    except IndexError:
        return default

def play(somefile):
    os.system('mpv --fs "' + somefile + '"')

def log(some_string, file=sys.stderr):
    print(some_string, file=file)

def update():
    url = 'https://raw.githubusercontent.com/L3viathan/scripts/master/episode'
    log("Trying to update this script...")
    r = requests.get(url, timeout=5)
    if r.status_code == 200:
        log("Response ok, writing to file")
        with open(__file__, 'w') as script:
            script.write(r.text)
    else:
        log("Failed.")

def get_id():
    try:
        last = int(open(hidden_data).read())
        return last
    except FileNotFoundError:
        try:
            os.remove(hidden_data)
        except FileNotFoundError:
            pass
        finally:
            return None

def set_id(_id):
    try:
        open(hidden_data,"w").write(str(int(_id)))
    except:
        log("Can only set to integer")

w = not args["--dry-run"]

if args["watch"] or args["play"]:
    if args["EPISODE"]:
        for id_, episode in enumerate(episodes):
            if args["EPISODE"].lower() in episode.lower():
                this_episode = id_
    else:
        last_episode = get_id()
        if last_episode is not None:
            this_episode = last_episode + 1
        else:
            this_episode = 0
    if lget(episodes,this_episode, None) is not None:
        log("Playing {}".format(episodes[this_episode]))
        if w:
            play(episodes[this_episode])
            set_id(this_episode)
    else:
        log("Out of episodes. Run again to start from the beginning.")
        if w: os.remove(hidden_data)
elif args["update"]:
    update()
